# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YmUX9SgM88zjkdi7484v3zA59t5N7AT2
"""

# speed
# list
a = [i for i in range(10000000)]
b = [i for i in range(10000000,20000000)]

c = []
import time

start = time.time()
for i in range(len(a)):
  c.append(a[i] + b[i])
print(time.time()-start)

# numpy
import numpy as np
a = np.arange(10000000)
b = np.arange(10000000,20000000)

start = time.time()
c = a + b
print(time.time()-start)

import numpy as np
a = np.arange(12).reshape(4,3)
a

a[[0,2,4]]

#fancy indexing
a=np.random.randint(1,100,24).reshape(6,4)
a

a[[0,2,3,5]]

a[:,[0,2,3]]

#boolean indexing

a=np.random.randint(1,100,24).reshape(6,4)

a>50

a[a>50]

#find out even numbers
a % 2 == 0

a [a % 2 == 0]

(a>50) & (a % 2 == 0)

a[(a>50) & (a % 2 == 0)]

a[a % 7 == 0]

#BROADCASTING

a=np.arange(6).reshape(2,3)
b=np.arange(6,12).reshape(2,3)
print(a)
print(b)

print(a+b)

a=np.arange(6).reshape(2,3)
b=np.arange(3).reshape(1,3)
print(a)
print(b)

a=np.arange(6).reshape(2,3)
b=np.arange(3).reshape(1,3)
print(a)
print(b)

print(a+b)

a=np.arange(3).reshape(1,3)
b=np.arange(3).reshape(3,1)
print(a)
print(b)
print(a+b)

a=np.arange(3).reshape(1,3)
b=np.arange(4).reshape(4,1)
print(a)
print(b)
print(a+b)

a=np.array([1])
b=np.arange(4).reshape(2,2)
print(a)
print(b)
print(a+b)

"""Working with mathematical formulas

"""

a= np.arange(18)
np.sum(a)

np.sin(a)

#sigmoid
def sigmoid(array):
  return 1/(1+np.exp(-(array)))
a=np.arange(10)
sigmoid(a)

#mean squared error

actual = np.random.randint(1,50,25)
predicted = np.random.randint(1,50,25)

predicted

actual

def mse(actual,predicted):
  return np.mean((actual-predicted)**2)
mse(actual,predicted)

np.mean((actual-predicted)**2)

#Binary cross enthropy
def bce(actual,predicted):
  return -np.mean(actual*np.log(predicted)+(1-actual)*np.log(1-predicted))
bce(actual,predicted)

"""Working with missing values"""

a=np.array([1,2,3,4,np.nan,6])
a

np.isnan(a)

a[~np.isnan(a)]

#Plotting Graphs

#x=y
x = np.linspace(-10,10,100)
x

y = x
y

import matplotlib.pyplot as plt

plt.plot(x,y)

#y=x^2

x=np.linspace(-10,10,100)
y=x**2
plt.plot(x,y)

#y=sin(x)

x=np.linspace(-10,10,100)
y=np.sin(x)
plt.plot(x,y)

#y=xlog(x)
x=np.linspace(1,10,100)
y=x*np.log(x)
plt.plot(x,y)

#sigmoid
x=np.linspace(-10,10,100)
y=1/(1+np.exp(-x))
plt.plot(x,y)

